//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemoPages.CrimeDataService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CrimeDataService.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getCrimeData", ReplyAction="http://tempuri.org/IService1/getCrimeDataResponse")]
        int getCrimeData(double lon, double lat);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getCrimeData", ReplyAction="http://tempuri.org/IService1/getCrimeDataResponse")]
        System.Threading.Tasks.Task<int> getCrimeDataAsync(double lon, double lat);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : DemoPages.CrimeDataService.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<DemoPages.CrimeDataService.IService1>, DemoPages.CrimeDataService.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int getCrimeData(double lon, double lat) {
            return base.Channel.getCrimeData(lon, lat);
        }
        
        public System.Threading.Tasks.Task<int> getCrimeDataAsync(double lon, double lat) {
            return base.Channel.getCrimeDataAsync(lon, lat);
        }
    }
}
